Начинаем программировать
htmlacademy-react/2049477-six-cities-11 pull request #3
Opened 2022-10-30 19:15 UTC by AxlMonk

2022-11-06 09:39 UTC, Dima-Dim requested changes
Как `[package-lock.json](https://github.com/htmlacademy-react/2049477-six-cities-11/pull/3/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519)` оказался выше `project`?

2022-11-06 09:39 UTC, Dima-Dim commented on project/src/pages/favorites-page/favorites-page.tsx
> +    <html lang="en">
Тут кажется что-то лишнее. Тут же должна быть только уникальная часть разметки.

2022-11-06 17:08 UTC, AxlMonk commented
[package-lock.json](https://github.com/htmlacademy-react/2049477-six-cities-11/pull/3/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519) у меня ровненько расположен, внизу проекта

2022-11-07 13:36 UTC, Dima-Dim requested changes
Почему [package-lock.json](https://github.com/htmlacademy-react/2049477-six-cities-11/pull/3/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519) над `project`?

2022-11-08 16:07 UTC, Dima-Dim commented
Всё ещё "Почему [package-lock.json](https://github.com/htmlacademy-react/2049477-six-cities-11/pull/3/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519) над project?" :)

2022-11-09 05:05 UTC, AxlMonk commented
я немного не понимаю, что от меня требуется? Просто все папки у меня в проекте на своем месте, в гитхабе тоже все обычно отображается

2022-11-09 14:16 UTC, Dima-Dim commented
> я немного не понимаю, что от меня требуется? Просто все папки у меня в проекте на своем месте, в гитхабе тоже все обычно отображается

https://github.com/htmlacademy-react/2049477-six-cities-11/pull/3/files - тут у тебя тоже не отображается package-lock.json в корне проекта?
![image](https://user-images.githubusercontent.com/35235492/200853559-708d9fdd-4c9c-495e-bd3d-a3e911f4b44b.png)

2022-11-09 20:11 UTC, closed without merging